name: Alpine Package Builder
description: 'Builds an Alpine Linux package with the specified version'

author: Adam Jensen <acjensen@gmail.com>

secrets:
  - GITHUB_TOKEN

inputs:
  package_path:
    description: 'Path to the package to build (e.g., main/nginx)'
    required: true
  release_version:
    description: 'The version number to use when building the package'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'git-commit'
  color: blue